version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - TZ=UTC
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  athena-api:
    image: akeshmiri/athena-api-boot:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9090:9090"
    links:
      - postgres
    environment:
      - TZ=UTC
      - DB_PSQL_URL=jdbc:postgresql://postgres:5432/postgres?TC_INITSCRIPT=psql/create-schema.sql
      - DB_PSQL_USERNAME=postgres
      - DB_PSQL_PASSWORD=password
volumes:
  postgres:
    driver: local
