x-common-variables: &common-variables
  DB_PSQL_URL: "jdbc:postgresql://athena-db:5432/athena"
  JAEGER_HOSTNAME: "athena-jaeger"
  JAEGER_ENABLED: true

x-athena_core_dependent_service: &athena_core_dependent_service
  pull_policy: never
  restart: unless-stopped
  depends_on:
    - athena-db
    - athena-core
  environment: *common-variables

services:
  athena-db:
    image: akeshmiri/athena-pg-demo:0.2
    pull_policy: if_not_present
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - athena-db:/var/lib/postgresql/data

  athena-core:
    image: akeshmiri/athena-boot-core:latest
    pull_policy: never
    restart: always
    depends_on:
      - athena-db
    environment: *common-variables
    ports:
      - "8081:8081"

  athena-git:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-git:latest
    ports:
      - "8082:8082"

  athena-kube:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-kube:latest
    ports:
      - "8083:8083"

  athena-metric:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-metric:latest
    ports:
      - "8084:8084"

  athena-pipeline:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-pipeline:latest
    ports:
      - "8085:8085"

  athena-spec:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-spec:latest
    ports:
      - "8086:8086"

  athena-tms:
    <<: *athena_core_dependent_service
    image: akeshmiri/athena-boot-tms:latest
    ports:
      - "8087:8087"

  athena-gateway:
    image: akeshmiri/athena-gateway:latest
    pull_policy: never
    restart: unless-stopped
    depends_on:
      - athena-core
      - athena-git
      - athena-kube
      - athena-metric
      - athena-pipeline
      - athena-spec
      - athena-tms
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: path
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://athena-core:8081
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: athena-core
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /core/**
      SPRING_CLOUD_GATEWAY_ROUTES[0]_FILTERS[0]: StripPrefix=1

      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://athena-git:8082
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: athena-git
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path= /git/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_FILTERS[0]: StripPrefix=1

      SPRING_CLOUD_GATEWAY_ROUTES[2]_URI: http://athena-kube:8083
      SPRING_CLOUD_GATEWAY_ROUTES[2]_ID: athena-kube
      SPRING_CLOUD_GATEWAY_ROUTES[2]_PREDICATES[0]: Path= /kube/**
      SPRING_CLOUD_GATEWAY_ROUTES[2]_FILTERS[0]: StripPrefix=1

      SPRING_CLOUD_GATEWAY_ROUTES[3]_URI: http://athena-metric:8084
      SPRING_CLOUD_GATEWAY_ROUTES[3]_ID: athena-metric
      SPRING_CLOUD_GATEWAY_ROUTES[3]_PREDICATES[0]: Path= /metric/**
      SPRING_CLOUD_GATEWAY_ROUTES[3]_FILTERS[0]: StripPrefix=1

      SPRING_CLOUD_GATEWAY_ROUTES[4]_URI: http://athena-pipeline:8085
      SPRING_CLOUD_GATEWAY_ROUTES[4]_ID: athena-pipeline
      SPRING_CLOUD_GATEWAY_ROUTES[4]_PREDICATES[0]: Path= /pipeline/**
      SPRING_CLOUD_GATEWAY_ROUTES[4]_FILTERS[0]: StripPrefix=1

      SPRING_CLOUD_GATEWAY_ROUTES[5]_URI: http://athena-spec:8086
      SPRING_CLOUD_GATEWAY_ROUTES[5]_ID: athena-spec
      SPRING_CLOUD_GATEWAY_ROUTES[5]_PREDICATES[0]: Path= /spec/**
      SPRING_CLOUD_GATEWAY_ROUTES[5]_FILTERS[0]: StripPrefix=1

      SPRING_CLOUD_GATEWAY_ROUTES[6]_URI: http://athena-tms:8087
      SPRING_CLOUD_GATEWAY_ROUTES[6]_ID: athena-tms
      SPRING_CLOUD_GATEWAY_ROUTES[6]_PREDICATES[0]: Path= /tms/**
      SPRING_CLOUD_GATEWAY_ROUTES[6]_FILTERS[0]: StripPrefix=1

  athena-pgadmin:
    image: dpage/pgadmin4:latest
    pull_policy: if_not_present
    restart: unless-stopped
    depends_on:
      - athena-db
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@athena.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    user: root
    entrypoint: /bin/sh -c "chmod 0600 /pgpass; /entrypoint.sh;"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
      - source: pgpass
        target: /pgpass

  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  athena-jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - '16686:16686'
      - '4317:4317'
      - '4318:4318'
      - '5778:5778'
      - '9411:9411'
    pull_policy: if_not_present
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug

# ********************
# Compose Configurations
# ********************
configs:
  pgpass:
    content: athena-db:5432:athena:postgres:password
  servers.json:
    content: |
      {"Servers": {"1": {
        "Group": "Servers",
        "Name": "Athena DB",
        "Host": "athena-db",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "postgres",
        "PassFile": "/pgpass",
        "SSLMode": "prefer"
      }}}

volumes:
  athena-db:
  pgadmin-data:

networks:
  default:
    name: athena-network
    driver: bridge
  athena-network:
    driver: bridge